language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install coveralls

# command to run tests
script:
  - coverage run alphabet_test.py

after_success:
  - coveralls
